# Generated by Django 5.2.7 on 2025-10-23 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('invitations', '0010_invitation_is_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(db_index=True, max_length=254)),
                ('detection_source', models.CharField(choices=[('dedup_service', 'Deduplication Service'), ('db_check', 'Database Check')], max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_records', to='invitations.bulkuploadjob')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_records', to='adminapp.tickettype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guest_email', 'scope'], name='adminapp_du_guest_e_00b1f3_idx')],
            },
        ),
    ]
