# Generated by Django 5.2.7 on 2025-10-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationstats',
            name='allocated_invitations',
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='invitationstats',
            name='remaining_invitations',
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
