# Generated by Django 5.2.7 on 2025-10-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_invitationstats_allocated_invitations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
