# Generated by Django 5.2.7 on 2025-10-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_alter_invitation_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='link_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
