# Generated by Django 5.2.7 on 2025-10-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_invitation_link_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='link_limit_reached',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
