# Generated by Django 5.2.7 on 2025-10-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_alter_invitation_source_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportJob',
        ),
    ]
