# Generated by Django 5.2.7 on 2025-10-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('invitations', '0007_delete_exportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapp.tickettype'),
        ),
        migrations.RemoveConstraint(
            model_name='invitation',
            name='unique_invite_per_guest_per_ticket',
        ),
        migrations.AddField(
            model_name='invitation',
            name='global_unique_enforced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='ticket_unique_enforced',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
