# Generated by Django 5.2.7 on 2025-10-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_alter_invitation_ticket_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='global_unique_enforced',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='ticket_unique_enforced',
        ),
    ]
