# Generated by Django 5.2.7 on 2025-10-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0009_remove_invitation_global_unique_enforced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
