# Generated by Django 5.2.7 on 2025-10-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0010_invitation_is_sent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invitationstats',
            name='invitations_user_id_6d4a26_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitationstats',
            name='invitations_remaini_9a5423_idx',
        ),
        migrations.RemoveField(
            model_name='bulkuploadjob',
            name='sample_errors',
        ),
        migrations.RemoveField(
            model_name='invitationstats',
            name='user',
        ),
        migrations.AddField(
            model_name='bulkuploadjob',
            name='error_note',
            field=models.TextField(blank=True, default=list),
        ),
    ]
